name: Publish

on: [push]
#  push:
#    branches:
#      - "master"
#      - "develop"
#      - "manwe"
#      - "acer"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: .exe
            asset_name: openworld-desktop.exe

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.1.1
      with:
        path: openworld-desktop

    - name: Install
      working-directory: openworld-desktop
      run: npm install

    - name: Build
      working-directory: openworld-desktop
      run: npm run build

    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date +'%Y%m%d%H%M%S')"

    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"

    - name: Upload binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openworld-desktop/dist/openworld-desktop-${{ steps.extract_version.outputs.version }}${{ matrix.artifact_name }}
        asset_name: openworld-desktop-${{ steps.extract_version.outputs.version }}-${{ env.BRANCH_NAME }}-${{ env.NOW }}${{ matrix.artifact_name }}
        tag: v${{ steps.extract_version.outputs.version }}
